### Very Basic and easy to do, might not be useful with AI available

In [ ]:
import torch
import numpy as np

In [2]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
a = np.array([[1,2,3],[4,5,6]])
torch.tensor(a)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.zeros([2,3],dtype = torch.float16)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [12]:
#creates random with normal distribution
torch.randn([2,3],dtype = torch.float16)

#creates random with uniform distribution
torch.rand([2,3],dtype = torch.float16)

tensor([[ 1.0684,  0.7729,  1.1357],
        [-1.9609,  0.6841, -1.1982]], dtype=torch.float16)

In [15]:
# create tensor with same shape as another tensor
x = torch.randn([4,5])
torch.zeros_like(x)
ones = torch.ones_like(x)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [16]:
# transpose
ones.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
# works with an instance of the tensor values only
ones.new_full((2,2),3)

tensor([[3., 3.],
        [3., 3.]])

In [28]:
# Is True if the Tensor is stored on the GPU, False otherwise.
ones.is_cuda

False

In [29]:
# Is True if the Tensor is quantized, False otherwise.
ones.is_quantized

False

In [31]:
ones.ndim

2

In [34]:
ones.is_contiguous()

True

In [35]:
torch.cuda.is_available()

True

In [36]:
# element wise ops
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

c = a + b
d = a.mul(b)
e = a / b
f = a - b  
g = a.pow(b)  # a raised to the power of b

In [40]:
# 1D tensor
x = torch.tensor([10, 20, 30, 40, 50])

# Basic indexing
print("x[0] =", x[0])        # 10
print("x[-1] =", x[-1])      # 50

# Slicing
print("x[1:4] =", x[1:4])    # [20, 30, 40]
print("x[:3] =", x[:3])      # [10, 20, 30]
print("x[2:] =", x[2:])      # [30, 40, 50]

# Step slicing
print("x[::2] =", x[::2])    # [10, 30, 50]


x[0] = tensor(10)
x[-1] = tensor(50)
x[1:4] = tensor([20, 30, 40])
x[:3] = tensor([10, 20, 30])
x[2:] = tensor([30, 40, 50])
x[::2] = tensor([10, 30, 50])


In [41]:
# 2D tensor
m = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Indexing
print("m[0,0] =", m[0, 0])     # 1
print("m[1,2] =", m[1, 2])     # 6
print("m[-1,-1] =", m[-1, -1]) # 9

# Slicing
print("First row:", m[0, :])     # [1,2,3]
print("First column:", m[:, 0])  # [1,4,7]
print("Top-left block:", m[:2, :2])
print("Bottom-right block:", m[1:, 1:])


m[0,0] = tensor(1)
m[1,2] = tensor(6)
m[-1,-1] = tensor(9)
First row: tensor([1, 2, 3])
First column: tensor([1, 4, 7])
Top-left block: tensor([[1, 2],
        [4, 5]])
Bottom-right block: tensor([[5, 6],
        [8, 9]])


In [42]:
# Fancy indexing
print("Fancy:", x[[0, 3, 4]])    # [10, 40, 50]

# Boolean mask
mask = x > 25
print("Mask:", mask)
print("Masked values:", x[mask]) # values > 25

# Ellipsis for high-dimensional tensors
t = torch.randn(2, 3, 4, 5)
print("t[..., 0].shape =", t[..., 0].shape) # select all dimension not being mentioned

# Assignment / in-place updates
x_clone = x.clone()
x_clone[1:4] = 99
print("After assignment:", x_clone)


Fancy: tensor([10, 40, 50])
Mask: tensor([False, False,  True,  True,  True])
Masked values: tensor([30, 40, 50])
t[..., 0].shape = torch.Size([2, 3, 4])
After assignment: tensor([10, 99, 99, 99, 50])
